import {
  PARTS,
  parseValue,
  type CircuitDocument,
  type Analysis,
} from "./model";
export type NetMap = {
  byEndpoint: Map<string, string>;
  members: Map<string, string[]>;
};
export function connectivity(doc: CircuitDocument): NetMap {
  const parent = new Map<string, string>();
  const find = (x: string): string => {
    if (!parent.has(x)) throw new Error(`Missing terminal ${x}`);
    const p = parent.get(x)!;
    if (p !== x) parent.set(x, find(p));
    return parent.get(x)!;
  };
  const union = (a: string, b: string) => {
    const aa = find(a),
      bb = find(b);
    if (aa !== bb) parent.set(bb, aa);
  };
  for (const c of doc.components)
    for (const p of PARTS[c.kind].pins)
      parent.set(`${c.id}.${p.id}`, `${c.id}.${p.id}`);
  for (const j of doc.junctions) parent.set(j.id, j.id);
  // A current sensor breaks this connection; a zero-volt source joins the two nets.
  for (const w of doc.wires) if (!w.currentProbe) union(w.from, w.to);
  const ground = doc.components
    .filter((c) => c.kind === "G")
    .map((c) => `${c.id}.g`);
  const labels = new Map<string, string>();
  for (const j of doc.junctions) {
    if (!j.label?.trim()) continue;
    const label = j.label.trim().toLowerCase();
    if (!/^(0|[a-z_][a-z0-9_]*)$/.test(label))
      throw new Error(
        `Invalid net label “${j.label}”. Use letters, digits, and underscores.`,
      );
    if (label === "0") ground.push(j.id);
    if (labels.has(label)) union(j.id, labels.get(label)!);
    else labels.set(label, j.id);
  }
  ground.forEach((g) => union(ground[0], g));
  const groups = new Map<string, string[]>();
  for (const ref of [...parent.keys()].sort()) {
    const root = find(ref);
    groups.set(root, [...(groups.get(root) ?? []), ref]);
  }
  const byEndpoint = new Map<string, string>();
  const members = new Map<string, string[]>();
  let auto = 1;
  for (const [root, refs] of groups) {
    const names = [...labels.entries()]
      .filter(([, ref]) => find(ref) === root)
      .map(([name]) => name);
    const isGround = ground.some((g) => find(g) === root);
    if (names.length > 1 || (isGround && names.some((n) => n !== "0")))
      throw new Error(
        `Connected net labels conflict: ${names.join(", ")}${isGround ? " and ground" : ""}.`,
      );
    let name = isGround ? "0" : names[0];
    if (!name) {
      do {
        name = `n${String(auto++).padStart(3, "0")}`;
      } while (labels.has(name));
    }
    members.set(name, refs);
    refs.forEach((ref) => byEndpoint.set(ref, name));
  }
  return { byEndpoint, members };
}
export function analysisOptions(a: Analysis) {
  if (a.mode === "transient") {
    const step = parseValue(a.step),
      stop = parseValue(a.stop);
    if (step <= 0 || stop <= 0 || step > stop)
      throw new Error(
        "Transient step and stop must be positive, with step ≤ stop.",
      );
    if (stop / step > 1_000_000)
      throw new Error(
        "Choose a larger time step (maximum one million requested intervals).",
      );
    return { step, stop };
  }
  if (a.mode === "ac") {
    const start = parseValue(a.start),
      stop = parseValue(a.end);
    if (
      start <= 0 ||
      stop < start ||
      !Number.isInteger(a.points) ||
      a.points < 1 ||
      a.points > 10000
    )
      throw new Error(
        "AC needs positive frequencies, stop ≥ start, and 1–10,000 points.",
      );
    return { mode: a.sweep, points: a.points, start, stop };
  }
  return {};
}
export function analysisLine(a: Analysis): string {
  const o = analysisOptions(a);
  if (a.mode === "ac") return `.ac ${a.sweep} ${a.points} ${o.start} ${o.stop}`;
  if (a.mode === "transient") return `.tran ${o.step} ${o.stop}`;
  return ".op";
}
export function compile(
  doc: CircuitDocument,
  validate = true,
): { text: string; nets: NetMap } {
  analysisOptions(doc.analysis);
  if (doc.mode === "netlist")
    return {
      text: doc.text,
      nets: { byEndpoint: new Map(), members: new Map() },
    };
  const nets = connectivity(doc);
  const parts = doc.components.filter((c) => c.kind !== "G");
  if (validate && !parts.length)
    throw new Error("Add a source and a few components to begin.");
  if (validate && !nets.members.has("0"))
    throw new Error("Add a ground symbol and connect it to the circuit.");
  const touched = new Set(doc.wires.flatMap((w) => [w.from, w.to]));
  const usedModels = new Set<string>();
  const lines = [
    doc.title.replace(/[\r\n]/g, " ").replace(/^[.*]/, "Circuit ") ||
      "neospice circuit",
    "* Generated by neospice Circuit Lab",
  ];
  for (const c of parts) {
    const p = c.props;
    const num = (key: string, positive = false) => {
      const val = parseValue(p[key] ?? "");
      if (positive && val <= 0)
        throw new Error(`${c.id}: ${key} must be greater than zero.`);
      return val;
    };
    if (validate)
      for (const pin of PARTS[c.kind].pins)
        if (!touched.has(`${c.id}.${pin.id}`))
          throw new Error(`${c.id}: connect terminal ${pin.id}.`);
    const n = (pin: string) => nets.byEndpoint.get(`${c.id}.${pin}`)!;
    if (["R", "C", "L"].includes(c.kind))
      lines.push(`${c.id} ${n("a")} ${n("b")} ${num("value", true)}`);
    else if (c.kind === "V" || c.kind === "I") {
      let source = `${c.id} ${n("p")} ${n("n")} DC ${num("dc")} AC ${num("ac")} ${num("phase")}`;
      if (p.wave === "sin")
        source += ` SIN(${num("offset")} ${num("amplitude")} ${num("frequency", true)})`;
      else if (p.wave === "pulse") {
        for (const key of ["delay", "rise", "fall", "width"])
          if (num(key) < 0)
            throw new Error(`${c.id}: ${key} cannot be negative.`);
        if (num("width") > num("period", true))
          throw new Error(`${c.id}: pulse width cannot exceed its period.`);
        source += ` PULSE(${num("low")} ${num("high")} ${num("delay")} ${num("rise")} ${num("fall")} ${num("width")} ${num("period", true)})`;
      } else if (p.wave !== "dc") throw new Error(`${c.id}: unknown waveform.`);
      lines.push(source);
    } else if (c.kind === "OP")
      lines.push(
        `${c.id} ${n("out")} 0 ${n("plus")} ${n("minus")} ${num("value", true)}`,
      );
    else if (c.kind === "CMP")
      lines.push(
        `${c.id} ${n("plus")} ${n("minus")} ${n("vcc")} ${n("vee")} ${n("out")} NEOSPICE_LAB_CMP GAIN=${num("value", true)} RESPONSE=${num("response", true)}`,
      );
    else {
      if (!p.model || !Object.hasOwn(doc.models, p.model))
        throw new Error(`${c.id}: select an available inline model.`);
      usedModels.add(p.model);
      if (c.kind === "D") lines.push(`${c.id} ${n("a")} ${n("b")} ${p.model}`);
      else if (c.kind === "QN" || c.kind === "QP")
        lines.push(`${c.id} ${n("c")} ${n("b")} ${n("e")} ${p.model}`);
      else
        lines.push(
          `${c.id} ${n("d")} ${n("g")} ${n("s")} ${n("b")} ${p.model} W=${num("w", true)} L=${num("l", true)}`,
        );
    }
  }
  for (const w of doc.wires) {
    if (!w.currentProbe) continue;
    const a = nets.byEndpoint.get(w.from)!,
      b = nets.byEndpoint.get(w.to)!;
    if (a === b)
      throw new Error(
        "This current probe is bypassed by another wire or matching net labels. Place it on a single branch.",
      );
    const p = w.currentProbe;
    lines.push(`${p.id} ${p.reversed ? b : a} ${p.reversed ? a : b} DC 0`);
  }
  if (parts.some((c) => c.kind === "CMP"))
    lines.push(
      "* Simplified comparator: smooth rail-limited transfer, 10 ohm output, finite response.",
      ".subckt NEOSPICE_LAB_CMP plus minus vcc vee out params: GAIN=100 RESPONSE=5n",
      "Bdrive drive vee V={V(vcc,vee)/2*(1+tanh(GAIN*V(plus,minus)))}",
      "Rdrive drive out 10",
      "Cresponse out vee {RESPONSE/10}",
      ".ends NEOSPICE_LAB_CMP",
    );
  for (const model of [...usedModels].sort()) lines.push(doc.models[model]);
  const initial = new Map<string, number>();
  for (const j of doc.junctions)
    if (j.initial?.trim()) {
      const net = nets.byEndpoint.get(j.id)!;
      const value = parseValue(j.initial);
      if (initial.has(net) && initial.get(net) !== value)
        throw new Error(`Conflicting initial voltages on ${net}.`);
      initial.set(net, value);
    }
  if (initial.size)
    lines.push(
      ".ic " + [...initial].map(([name, v]) => `V(${name})=${v}`).join(" "),
    );
  lines.push(analysisLine(doc.analysis), ".end", "");
  return { text: lines.join("\n"), nets };
}
export function validateText(text: string) {
  if (!text.trim()) throw new Error("Enter a SPICE netlist first.");
  if (text.length > 2_000_000)
    throw new Error("Netlists must be smaller than 2 MB.");
  if (/^\s*\.(?:include|inc|lib)\b/im.test(text))
    throw new Error(
      "Inline model and subcircuit definitions in the netlist; external includes are unavailable in the browser.",
    );
  if (/^\s*\.(?:step|control)\b/im.test(text))
    throw new Error(
      "The browser runs the selected analysis. .step and .control blocks are unavailable.",
    );
}
