    // KiCad-Spice-Library E2E test: BC547A (NPN)
    // Auto-generated by tools/gen_kicad_test.py

    #include <gtest/gtest.h>
    #include "api/neospice.hpp"
    #include "framework/ngspice_runner.hpp"
    #include "framework/comparator.hpp"

    #include <cmath>
    #include <complex>
    #include <string>

    using namespace neospice;

    class KiCad_BC547A_Test : public ::testing::Test {
    protected:
        void SetUp() override {
            cir_path_ = std::string(TEST_CIRCUITS_DIR) + "/bc547a_test.cir";
            ngspice_ = std::make_unique<NgspiceRunner>();
        }
        std::string cir_path_;
        std::unique_ptr<NgspiceRunner> ngspice_;
        Simulator sim_;
    };

    TEST_F(KiCad_BC547A_Test, DCOperatingPoint) {
        auto ckt = sim_.load(cir_path_);
        auto dc = sim_.run_dc(ckt);

        double v_col = dc.voltage("col");
double v_base = dc.voltage("base");
double v_emit = dc.voltage("emit");

// BJT should be in active region
EXPECT_GT(v_col, v_emit)
    << "Collector should be above emitter in active region";

// Base-emitter voltage ~0.6-0.7V
double vbe = v_base - v_emit;
EXPECT_NEAR(vbe, 0.65, 0.15)
    << "Vbe should be ~0.65V, got " << vbe;
    }

    TEST_F(KiCad_BC547A_Test, ACResponse) {
        auto ckt = sim_.load(cir_path_);
        auto ac = sim_.run_ac(ckt, AnalysisCommand::DEC, 10, 10.0, 10e6);

        ASSERT_FALSE(ac.frequency.empty());
        ASSERT_TRUE(ac.voltages.count("v(out)") > 0);

        const auto& v_out = ac.voltage("out");

// CE amp should have voltage gain > 1 at mid-frequencies
double gain_mid = std::abs(v_out[v_out.size() / 2]);
EXPECT_GT(gain_mid, 1.0)
    << "CE amp mid-band gain should be > 1";
    }

    TEST_F(KiCad_BC547A_Test, NgspiceDCComparison) {
        DCResult ng_result;
        try {
            ng_result = ngspice_->run_dc(cir_path_);
        } catch (const std::exception& e) {
            GTEST_SKIP() << "ngspice not available: " << e.what();
        }

        auto ckt = sim_.load(cir_path_);
        auto neo_result = sim_.run_dc(ckt);

        auto cmp = compare_dc(ng_result, neo_result, {1e-2, 1e-6});
        EXPECT_TRUE(cmp.passed)
            << "DC comparison failed. Worst: " << cmp.worst_signal
            << " error: " << cmp.worst_error;
    }

    TEST_F(KiCad_BC547A_Test, NgspiceACComparison) {
        ACResult ng_result;
        try {
            ng_result = ngspice_->run_ac(cir_path_);
        } catch (const std::exception& e) {
            GTEST_SKIP() << "ngspice not available: " << e.what();
        }

        if (ng_result.frequency.empty()) {
            GTEST_SKIP() << "ngspice returned empty AC result";
        }

        auto ckt = sim_.load(cir_path_);
        auto neo_result = sim_.run_ac(ckt, AnalysisCommand::DEC, 10, 10.0, 10e6);

        ASSERT_FALSE(neo_result.frequency.empty());
        ASSERT_EQ(ng_result.frequency.size(), neo_result.frequency.size());

        ACResult ng_filtered;
        ng_filtered.frequency = ng_result.frequency;
        for (const auto& [name, data] : ng_result.voltages) {
            ng_filtered.voltages[name] = data;
        }
        auto cmp = compare_ac(ng_filtered, neo_result, {1e-2, 1e-6});
        EXPECT_TRUE(cmp.passed)
            << "AC comparison failed. Worst: " << cmp.worst_signal
            << " error: " << cmp.worst_error;
    }
