    // KiCad-Spice-Library E2E test: LM358/NS (SUBCKT)
    // Auto-generated by tools/gen_kicad_test.py

    #include <gtest/gtest.h>
    #include "api/neospice.hpp"
    #include "framework/ngspice_runner.hpp"
    #include "framework/comparator.hpp"

    #include <cmath>
    #include <complex>
    #include <string>

    using namespace neospice;

    class KiCad_LM358_NS_Test : public ::testing::Test {
    protected:
        void SetUp() override {
            cir_path_ = std::string(TEST_CIRCUITS_DIR) + "/lm358_ns_test.cir";
            ngspice_ = std::make_unique<NgspiceRunner>();
        }
        std::string cir_path_;
        std::unique_ptr<NgspiceRunner> ngspice_;
        Simulator sim_;
    };

    TEST_F(KiCad_LM358_NS_Test, DCOperatingPoint) {
        auto ckt = sim_.load(cir_path_);
        auto dc = sim_.run_dc(ckt);

        double v_out = dc.voltage("out");
double v_inv = dc.voltage("inv");
double v_ninv = dc.voltage("ninv");

// Inverting amp: virtual ground at inv ≈ ninv
EXPECT_NEAR(v_inv, v_ninv, 0.05)
    << "Virtual ground: inv=" << v_inv << " ninv=" << v_ninv;

// Output should be approximately -gain * Vin + bias
// With gain=-10 and Vin=50mV: Vout ≈ bias - 0.5V
// Just check output is in a reasonable range
EXPECT_GT(std::abs(v_out), 0.01)
    << "Output should be nonzero, got " << v_out;
    }

    TEST_F(KiCad_LM358_NS_Test, ACResponse) {
        auto ckt = sim_.load(cir_path_);
        auto ac = sim_.run_ac(ckt, AnalysisCommand::DEC, 10, 1.0, 10e6);

        ASSERT_FALSE(ac.frequency.empty());
        ASSERT_TRUE(ac.voltages.count("v(out)") > 0);

        const auto& v_out = ac.voltage("out");

// Low-frequency gain should be ~20 dB (gain of 10)
double gain_low = 20.0 * std::log10(std::max(std::abs(v_out[0]), 1e-20));
EXPECT_NEAR(gain_low, 20.0, 1.0)
    << "Low-freq gain should be ~20 dB, got " << gain_low;

// High-frequency gain should roll off
double gain_high = 20.0 * std::log10(std::max(std::abs(v_out.back()), 1e-20));
EXPECT_LT(gain_high, gain_low - 3.0)
    << "Gain at max freq should be < low-freq gain - 3dB";
    }

    TEST_F(KiCad_LM358_NS_Test, NgspiceDCComparison) {
        DCResult ng_result;
        try {
            ng_result = ngspice_->run_dc(cir_path_);
        } catch (const std::exception& e) {
            GTEST_SKIP() << "ngspice not available: " << e.what();
        }

        auto ckt = sim_.load(cir_path_);
        auto neo_result = sim_.run_dc(ckt);

        auto cmp = compare_dc(ng_result, neo_result, {1e-2, 1e-6});
        EXPECT_TRUE(cmp.passed)
            << "DC comparison failed. Worst: " << cmp.worst_signal
            << " error: " << cmp.worst_error;
    }

    TEST_F(KiCad_LM358_NS_Test, NgspiceACComparison) {
        ACResult ng_result;
        try {
            ng_result = ngspice_->run_ac(cir_path_);
        } catch (const std::exception& e) {
            GTEST_SKIP() << "ngspice not available: " << e.what();
        }

        if (ng_result.frequency.empty()) {
            GTEST_SKIP() << "ngspice returned empty AC result";
        }

        auto ckt = sim_.load(cir_path_);
        auto neo_result = sim_.run_ac(ckt, AnalysisCommand::DEC, 10, 1.0, 10e6);

        ASSERT_FALSE(neo_result.frequency.empty());
        ASSERT_EQ(ng_result.frequency.size(), neo_result.frequency.size());

        ACResult ng_filtered;
        ng_filtered.frequency = ng_result.frequency;
        for (const auto& [name, data] : ng_result.voltages) {
            ng_filtered.voltages[name] = data;
        }
        auto cmp = compare_ac(ng_filtered, neo_result, {1e-2, 1e-6});
        EXPECT_TRUE(cmp.passed)
            << "AC comparison failed. Worst: " << cmp.worst_signal
            << " error: " << cmp.worst_error;
    }
