// KiCad-Spice-Library E2E test: OPA1632 (SUBCKT)
// Fully-differential amplifier, 8-pin, 357 elements
// Auto-generated by tools/gen_kicad_test.py, hand-tuned for diff-amp topology

#include <gtest/gtest.h>
#include "api/neospice.hpp"
#include "framework/ngspice_runner.hpp"
#include "framework/comparator.hpp"

#include <cmath>
#include <complex>
#include <string>

using namespace neospice;

class KiCad_OPA1632_Test : public ::testing::Test {
protected:
    void SetUp() override {
        cir_path_ = std::string(TEST_CIRCUITS_DIR) + "/opa1632_test.cir";
        ngspice_ = std::make_unique<NgspiceRunner>();
    }
    std::string cir_path_;
    std::unique_ptr<NgspiceRunner> ngspice_;
    Simulator sim_;
};

TEST_F(KiCad_OPA1632_Test, DCOperatingPoint) {
    auto ckt = sim_.load(cir_path_);
    auto dc = sim_.run_dc(ckt);

    double v_outp = dc.voltage("outp");
    double v_outn = dc.voltage("outn");
    double v_vinp = dc.voltage("vinp");
    double v_vinn = dc.voltage("vinn");

    // Unity gain (Rf/Rg=1): differential output ≈ -(Vin_diff)
    // Input: Vin=0.1V single-ended → outp-outn ≈ -0.1V
    double v_diff = v_outp - v_outn;
    EXPECT_NEAR(v_diff, -0.1, 0.02)
        << "Differential output: outp=" << v_outp << " outn=" << v_outn
        << " diff=" << v_diff;

    // Common mode should be near 0V (VOCM tied to ground)
    double v_cm = (v_outp + v_outn) / 2.0;
    EXPECT_NEAR(v_cm, 0.0, 0.05)
        << "Common mode: " << v_cm;

    // Virtual ground: feedback forces vinp ≈ vinn
    EXPECT_NEAR(v_vinp, v_vinn, 0.05)
        << "Virtual ground: vinp=" << v_vinp << " vinn=" << v_vinn;
}

TEST_F(KiCad_OPA1632_Test, ACResponse) {
    auto ckt = sim_.load(cir_path_);
    auto ac = sim_.run_ac(ckt, AnalysisCommand::DEC, 10, 1.0, 100e6);

    ASSERT_FALSE(ac.frequency.empty());

    // Check differential output: v(outp) - v(outn)
    ASSERT_TRUE(ac.voltages.count("v(outp)") > 0);
    ASSERT_TRUE(ac.voltages.count("v(outn)") > 0);

    const auto& v_outp = ac.voltages.at("v(outp)");
    const auto& v_outn = ac.voltages.at("v(outn)");

    // Low-frequency differential gain should be ~0 dB (unity gain)
    std::complex<double> diff_low = v_outp[0] - v_outn[0];
    double gain_low = 20.0 * std::log10(std::max(std::abs(diff_low), 1e-20));
    EXPECT_NEAR(gain_low, 0.0, 1.5)
        << "Low-freq differential gain should be ~0 dB, got " << gain_low;

    // High-frequency gain should roll off
    std::complex<double> diff_high = v_outp.back() - v_outn.back();
    double gain_high = 20.0 * std::log10(std::max(std::abs(diff_high), 1e-20));
    EXPECT_LT(gain_high, gain_low - 3.0)
        << "Gain at 100MHz should be < low-freq gain - 3dB";
}

TEST_F(KiCad_OPA1632_Test, NgspiceDCComparison) {
    DCResult ng_result;
    try {
        ng_result = ngspice_->run_dc(cir_path_);
    } catch (const std::exception& e) {
        GTEST_SKIP() << "ngspice not available: " << e.what();
    }

    auto ckt = sim_.load(cir_path_);
    auto neo_result = sim_.run_dc(ckt);

    // Compare only external nodes (skip internal subcircuit nodes x1.*)
    DCResult ng_ext, neo_ext;
    for (const auto& [name, val] : ng_result.node_voltages) {
        if (name.find("x1.") == std::string::npos)
            ng_ext.node_voltages[name] = val;
    }
    for (const auto& [name, val] : neo_result.node_voltages) {
        if (name.find("x1.") == std::string::npos)
            neo_ext.node_voltages[name] = val;
    }
    ng_ext.branch_currents = ng_result.branch_currents;
    neo_ext.branch_currents = neo_result.branch_currents;

    auto cmp = compare_dc(ng_ext, neo_ext, {1e-2, 1e-6});
    EXPECT_TRUE(cmp.passed)
        << "DC comparison failed. Worst: " << cmp.worst_signal
        << " error: " << cmp.worst_error;
}

TEST_F(KiCad_OPA1632_Test, NgspiceACComparison) {
    ACResult ng_result;
    try {
        ng_result = ngspice_->run_ac(cir_path_);
    } catch (const std::exception& e) {
        GTEST_SKIP() << "ngspice not available: " << e.what();
    }

    if (ng_result.frequency.empty()) {
        GTEST_SKIP() << "ngspice returned empty AC result";
    }

    auto ckt = sim_.load(cir_path_);
    auto neo_result = sim_.run_ac(ckt, AnalysisCommand::DEC, 10, 1.0, 100e6);

    ASSERT_FALSE(neo_result.frequency.empty());
    ASSERT_EQ(ng_result.frequency.size(), neo_result.frequency.size());

    // Compare only external nodes (skip internal subcircuit nodes x1.*)
    ACResult ng_ext, neo_ext;
    ng_ext.frequency = ng_result.frequency;
    neo_ext.frequency = neo_result.frequency;
    for (const auto& [name, data] : ng_result.voltages) {
        if (name.find("x1.") == std::string::npos)
            ng_ext.voltages[name] = data;
    }
    for (const auto& [name, data] : neo_result.voltages) {
        if (name.find("x1.") == std::string::npos)
            neo_ext.voltages[name] = data;
    }

    auto cmp = compare_ac(ng_ext, neo_ext, {1e-2, 1e-6});
    EXPECT_TRUE(cmp.passed)
        << "AC comparison failed. Worst: " << cmp.worst_signal
        << " error: " << cmp.worst_error;
}
